"""Shareable RCA report for a case — Markdown or standalone HTML.

Both formats are built from the same data and run every shared string through a
redactor (default on) so the output is safe to attach to a ticket or hand to a
colleague. HTML is self-contained (inline CSS, no assets) for easy handoff.
"""

from __future__ import annotations

import html
import sqlite3

from rca.models import SEVERITY_RANK
from rca.redact import build_redactor
from rca.ruleset import CONFIDENCE_RANK
from rca.timeutil import format_offset
from rca.util import now_utc_iso


def _gather(conn: sqlite3.Connection, case_id: int) -> dict | None:
    case = conn.execute("SELECT * FROM cases WHERE id = ?", (case_id,)).fetchone()
    if case is None:
        return None
    bundle = conn.execute(
        "SELECT * FROM bundles WHERE case_id = ? ORDER BY id LIMIT 1", (case_id,)).fetchone()
    by_source = conn.execute(
        "SELECT source, COUNT(*) n FROM events WHERE case_id = ? GROUP BY source ORDER BY n DESC",
        (case_id,)).fetchall()
    findings = conn.execute(
        """SELECT f.id, f.severity, f.confidence, f.title, f.summary, f.recommendation
           FROM findings f WHERE f.case_id = ? """, (case_id,)).fetchall()
    findings = sorted(findings, key=lambda r: (SEVERITY_RANK.get(r["severity"], 0),
                                               CONFIDENCE_RANK.get(r["confidence"], 0)), reverse=True)
    evidence = {}
    for f in findings:
        evidence[f["id"]] = conn.execute(
            """SELECT e.ts_local, e.ts_utc, e.source, e.event_code, e.message
               FROM finding_evidence fe JOIN events e ON e.id = fe.event_id
               WHERE fe.finding_id = ? ORDER BY e.ts_utc LIMIT 5""", (f["id"],)).fetchall()
    tz = format_offset(bundle["tz_offset_minutes"]) if bundle else "UTC?"
    return {"case": case, "bundle": bundle, "by_source": by_source,
            "findings": findings, "evidence": evidence, "tz": tz}


def render_markdown(conn: sqlite3.Connection, case_id: int, redact: bool = True) -> str | None:
    data = _gather(conn, case_id)
    if data is None:
        return None
    R = build_redactor(conn, case_id).scrub if redact else (lambda s: s or "")
    c, b = data["case"], data["bundle"]
    L: list[str] = [f"# RCA Report — Case {case_id}", ""]
    L.append(f"**Symptom:** {R(c['symptom_text'])}")
    if b:
        L.append(f"**Machine:** {R(b['machine_name']) or '?'} · **Collected:** "
                 f"{b['collected_utc'] or '?'} · **Device TZ:** {data['tz']}")
    counts = ", ".join(f"{s['source']}={s['n']}" for s in data["by_source"]) or "none parsed"
    L.append(f"**Events:** {counts}")
    L.append(f"**Generated:** {now_utc_iso()}{'  ·  redacted' if redact else '  ·  NOT redacted'}")
    L += ["", "## Findings", ""]
    if not data["findings"]:
        L.append("_No findings — run analyze._")
    for f in data["findings"]:
        L.append(f"### [{f['severity']}/{f['confidence']}] {R(f['title'])}")
        L.append(R(f["summary"]) or "")
        L.append(f"**Fix:** {R(f['recommendation'])}")
        ev = data["evidence"].get(f["id"], [])
        if ev:
            L.append("")
            L.append("Evidence:")
            for e in ev:
                ts = e["ts_local"] or e["ts_utc"] or "?"
                L.append(f"- `{ts}` {e['source']} {e['event_code'] or ''} — "
                         f"{R(e['message'])[:200]}")
        L.append("")
    L.append("---")
    L.append("_Generated by Intune RCA._")
    return "\n".join(L)


_HTML_CSS = """
body{font:14px/1.55 system-ui,Segoe UI,Roboto,sans-serif;color:#1b1f24;max-width:880px;
margin:2rem auto;padding:0 1rem;background:#fff}
h1{font-size:1.5rem;margin:.2rem 0}h2{border-bottom:2px solid #e5e7eb;padding-bottom:.3rem;margin-top:1.6rem}
h3{margin:1.1rem 0 .2rem}.meta{color:#555;background:#f6f7f9;border:1px solid #e5e7eb;border-radius:8px;padding:.6rem .9rem}
.meta b{color:#1b1f24}.f{border:1px solid #e5e7eb;border-radius:8px;padding:.2rem 1rem 1rem;margin:.8rem 0}
.badge{display:inline-block;padding:.05em .55em;border-radius:999px;font-size:.78rem;font-weight:700}
.error,.critical{background:#fde2e1;color:#b42318}.warn{background:#fdf0d5;color:#9a6700}.info{background:#eef1f4;color:#555}
.fix{background:#f0f7ff;border-left:3px solid #1f6feb;padding:.4rem .7rem;margin:.5rem 0}
ul.ev{margin:.3rem 0;padding-left:1.1rem}ul.ev li{margin:.15rem 0}
code,.mono{font-family:ui-monospace,Consolas,monospace;font-size:.85em;background:#f1f3f5;padding:.05em .35em;border-radius:4px}
.foot{color:#888;font-size:.82rem;margin-top:2rem}
"""


def render_html(conn: sqlite3.Connection, case_id: int, redact: bool = True) -> str | None:
    data = _gather(conn, case_id)
    if data is None:
        return None
    R = build_redactor(conn, case_id).scrub if redact else (lambda s: s or "")
    def E(s):  # redact then HTML-escape
        return html.escape(R(s))
    c, b = data["case"], data["bundle"]
    counts = ", ".join(f"{s['source']}={s['n']}" for s in data["by_source"]) or "none parsed"
    parts = [f"<!doctype html><html><head><meta charset='utf-8'>",
             f"<title>RCA Case {case_id}</title><style>{_HTML_CSS}</style></head><body>",
             f"<h1>RCA Report — Case {case_id}</h1>",
             "<div class='meta'>",
             f"<div><b>Symptom:</b> {E(c['symptom_text'])}</div>"]
    if b:
        parts.append(f"<div><b>Machine:</b> {E(b['machine_name']) or '?'} &middot; "
                     f"<b>Collected:</b> {html.escape(b['collected_utc'] or '?')} &middot; "
                     f"<b>Device TZ:</b> {data['tz']}</div>")
    parts.append(f"<div><b>Events:</b> {html.escape(counts)}</div>")
    parts.append(f"<div><b>Generated:</b> {now_utc_iso()} &middot; "
                 f"{'redacted' if redact else '<b>NOT redacted</b>'}</div></div>")
    parts.append("<h2>Findings</h2>")
    if not data["findings"]:
        parts.append("<p><em>No findings — run analyze.</em></p>")
    for f in data["findings"]:
        sev = html.escape(f["severity"])
        parts.append(f"<div class='f'><h3><span class='badge {sev}'>{sev}</span> "
                     f"{E(f['title'])} <small>({html.escape(f['confidence'])} confidence)</small></h3>")
        parts.append(f"<p>{E(f['summary'])}</p>")
        parts.append(f"<div class='fix'><b>Fix:</b> {E(f['recommendation'])}</div>")
        ev = data["evidence"].get(f["id"], [])
        if ev:
            parts.append("<ul class='ev'>")
            for e in ev:
                ts = html.escape(e["ts_local"] or e["ts_utc"] or "?")
                parts.append(f"<li><span class='mono'>{ts}</span> {html.escape(e['source'])} "
                             f"<span class='mono'>{html.escape(e['event_code'] or '')}</span> — "
                             f"{E(e['message'])[:200]}</li>")
            parts.append("</ul>")
        parts.append("</div>")
    parts.append("<p class='foot'>Generated by Intune RCA.</p></body></html>")
    return "".join(parts)
