# OpenDriverUpdater - Intune detection script for the Pilot profile.
# GENERATED by setup.ps1 from driverConfig.json - do not hand-edit; re-run setup.ps1 after any config change.
#
# Reads everything it can from the CACHED package's driverConfig.json (Install copies the whole package, config
# included, to $PackageDir), so only three values live here:
#   $PackageDir      - where Install caches the package (= stateDir\Package from driverConfig.json). The one path this
#                      script must know in order to find the config.
#   $ExpectedProfile - this app's profile (deploy one Intune app per profile, each with its matching script).
#   $ExpectedVersion - MUST stay here, NOT be read from the JSON: it is the redeploy trigger. Intune delivers this
#                      script fresh with each app version, so it carries the NEW version. The cached config on an old
#                      device only knows the OLD version - and so does the registry - so reading it from the cache would
#                      always agree with the registry and a version bump would never reinstall. setup.ps1 keeps it in
#                      step with packageVersion in driverConfig.json for you.
#
# Contract: write to stdout when installed; output nothing when not. Write-Output (not Write-Host) so the result is
# on the pipeline for in-process callers and on stdout for Intune alike.

$PackageDir      = "$env:ProgramData\Contoso\DriverUpdates\Package"   # = stateDir\Package from driverConfig.json
$ExpectedProfile = 'Pilot'
$ExpectedVersion = '1.0.0'                                        # = packageVersion in driverConfig.json

# No cached package (or an unreadable config) means NOT installed - a reinstall repairs either. A bare `return` emits
# nothing, and Intune's contract is "exit 0 + empty stdout = not installed", so silence IS the not-installed answer.
# Only the explicit Write-Output 'Installed' at the very end ever reports installed.
$cfgPath = Join-Path $PackageDir 'driverConfig.json'
if (-not (Test-Path -LiteralPath $cfgPath)) { return }
try { $cfg = Get-Content -LiteralPath $cfgPath -Raw | ConvertFrom-Json } catch { return }

$Launcher = Join-Path $PackageDir 'Invoke-AppDeployToolkit.exe'
$Worker   = Join-Path $PackageDir 'SupportFiles\Invoke-DriverUpdate.ps1'
$task = Get-ScheduledTask -TaskName "$($cfg.taskName)" -ErrorAction SilentlyContinue
# Read the 64-bit hive explicitly: state lives under the 64-bit view, and if Intune ever runs this script as a 32-bit
# process, HKLM:\SOFTWARE\<Org> would silently redirect to WOW6432Node, report "not installed", and reinstall forever.
$hive = [Microsoft.Win32.RegistryKey]::OpenBaseKey([Microsoft.Win32.RegistryHive]::LocalMachine, [Microsoft.Win32.RegistryView]::Registry64)
$key  = $hive.OpenSubKey(("$($cfg.registryRoot)" -replace '^HKLM:\\', ''))
$regProfile = if ($key) { $key.GetValue('Profile') }
$regVersion = if ($key) { $key.GetValue('PackageVersion') }

if ($null -ne $task -and (Test-Path -LiteralPath $Launcher) -and (Test-Path -LiteralPath $Worker) -and
    $regProfile -eq $ExpectedProfile -and $regVersion -eq $ExpectedVersion) {
    Write-Output 'Installed'
}
