<#
.DESCRIPTION
	This script performs network drive mappings with PowerShell and is auto generated by the intune-drive-mapping-generator (https://intunedrivemapping.azurewebsites.net).
	When executed under SYSTEM authority a scheduled task is created to ensure recurring script execution on each user logon.

.NOTES
	Original Author: Nicola Suter, nicolonsky tech: https://tech.nicolonsky.ch
	Modified by JustSomeITAdmin
#>

[CmdletBinding()]
Param()

###########################################################################################
# Start transcript for logging
###########################################################################################

Start-Transcript -Path $(Join-Path $env:temp "DriveMapping.log")

###########################################################################################
# Input values from generator
###########################################################################################

#Very important to use single quotes so the variables can be evaluated
$driveMappingJson = @'
[
    {
        "Path":  "\\\\share\\to\\path\\Faculty\\$env:username",
        "DriveLetter":  "H",
        "Label":  "Home",
        "Id":  1,
        "GroupFilter":  "Faculty Share Access"
    },
    {
        "Path":  "\\\\share\\to\\path\\Students\\$env:username",
        "DriveLetter":  "H",
        "Label":  "Home",
        "Id":  2,
        "GroupFilter":  "Student Share Access"
    },
    {
        "Path":  "\\\\share\\to\\path\\Students\\Research",
        "DriveLetter":  "R",
        "Label":  "Research",
        "Id":  3,
        "GroupFilter":  "Research Share Access"
    }
]
'@

$driveMappingConfig = $driveMappingJson | ConvertFrom-Json -ErrorAction Stop
#used to create an array for groups
$driveMappingConfig = foreach ($d in $driveMappingConfig) {
	[PSCustomObject]@{
		Path        = $($d.Path)
		DriveLetter = $($d.DriveLetter)
		Label       = $($d.Label)
		Id          = $($d.Id)
		GroupFilter = $($d.GroupFilter -split ",")
	}
}
# Create a hash table of drives with corrected paths
$drives = @{}
foreach ($drive in $driveMappingConfig) {
	$driveLetter = $drive.DriveLetter + ":"
	$drives[$driveLetter] = $drive.Path -replace "\\\\", "\\"  # Correct double backslashes in each Path here
}

# Loop through each drive and check if it is mapped correctly
foreach ($drive in $drives.GetEnumerator()) {
	$driveLetter = $drive.Key
	$correctPath = $ExecutionContext.InvokeCommand.ExpandString($drive.Value)

	# Check if the drive is currently mapped
	$mappedDrive = Get-WmiObject -Query "SELECT * FROM Win32_NetworkConnection WHERE LocalName = '$driveLetter'" -ErrorAction SilentlyContinue

	if ($mappedDrive) {
		# If the drive is mapped, check if the UNC path is correct
		if ($mappedDrive.RemoteName -ne $correctPath) {
			Write-Host "The path for $driveLetter is incorrect. Removing drive."
			# Remove the drive if the path is incorrect
			cmd /c "net use $driveLetter /delete /yes"
		}
		else {
			Write-Host "The path for $driveLetter is correct."
		}
	}
 else {
		Write-Host "$driveLetter is not mapped."
	}
}
# Override with your Active Directory Domain Name e.g. 'ds.nicolonsky.ch' if you haven't configured the domain name as DHCP option
$searchRoot = ""

# If enabled all mounted PSdrives from filesystem except os drives get disconnected if not specified in drivemapping config
$removeStaleDrives = $false

###########################################################################################
# Helper function to determine a users group membership
###########################################################################################

# Kudos for Tobias Renström who showed me this!
function Get-ADGroupMembership {
	param(
		[parameter(Mandatory = $true)]
		[string]$UserPrincipalName
	)

	process {
		try {
			if ([string]::IsNullOrEmpty($env:USERDNSDOMAIN) -and [string]::IsNullOrEmpty($searchRoot)) {
				Write-Error "Security group filtering won't work because `$env:USERDNSDOMAIN is not available!"
				Write-Warning "You can override your AD Domain in the `$overrideUserDnsDomain variable"
			}
			else {
				if ([string]::IsNullOrEmpty($searchRoot)) {
					$searchRoot = $env:USERDNSDOMAIN
				}

				$searcher = New-Object -TypeName System.DirectoryServices.DirectorySearcher
				$searcher.SearchRoot = "LDAP://$searchRoot"

				# Find the user's DN
				$searcher.Filter = "(&(userprincipalname=$UserPrincipalName))"
				$userResult = $searcher.FindOne()
				$userDN = [string]$userResult.Properties.distinguishedname

				# Bind directly to the user and request tokenGroups
				# tokenGroups is a constructed attribute - requires a base-scoped search
				$userEntry = New-Object System.DirectoryServices.DirectoryEntry("LDAP://$userDN")
				$userEntry.RefreshCache(@("tokenGroups"))

				# Convert each SID to a group name via a single LDAP lookup
				$list = [System.Collections.Generic.List[String]]@()

				foreach ($sidBytes in $userEntry.Properties["tokenGroups"]) {
					$sid = New-Object System.Security.Principal.SecurityIdentifier($sidBytes, 0)

					# Resolve SID to group name using a SID-bound LDAP query
					$sidSearcher = New-Object System.DirectoryServices.DirectorySearcher
					$sidSearcher.SearchRoot = "LDAP://$searchRoot"
					$sidSearcher.Filter = "(objectSid=$sid)"
					[void]$sidSearcher.PropertiesToLoad.Add("name")

					$groupResult = $sidSearcher.FindOne()
					if ($groupResult) {
						[void]$list.Add([string]$groupResult.Properties.name)
					}
				}

				$list
			}
		}
		catch {
			Write-Warning $_.Exception.Message
		}
	}
}

#check if running as system
function Test-RunningAsSystem {
	[CmdletBinding()]
	param()
	process {
		return [bool]($(whoami -user) -match "S-1-5-18")
	}
}


#Testing if groupmembership is given for user
function Test-GroupMembership {
	[CmdletBinding()]
	param (
		$driveMappingConfig,
		$groupMemberships
	)
	try {
		$obj = foreach ($d in $driveMappingConfig) {
			if (-not ([string]::IsNullOrEmpty($($d.GroupFilter)))) {
				foreach ($filter in $($d.GroupFilter)) {
					if ($groupMemberships -contains $filter) {
						$d
					}
					else {
						#no match for group
					}
				}
			}
			else {
				$d 
			}
		}
		$obj
	}
	catch {
		Write-Error "Unknown error testing group memberships: $($_.Exception.Message)"
	}
}

###########################################################################################
# Get current group membership for the group filter capabilities
###########################################################################################

Write-Output "Running as SYSTEM: $(Test-RunningAsSystem)"

if ($driveMappingConfig.GroupFilter) {
	try {
		#check if running as user and not system
		if (-not (Test-RunningAsSystem)) {

			$groupMemberships = Get-ADGroupMembership -UserPrincipalName $(whoami -upn)
		}
	}
	catch {
		#nothing we can do
	}
}
###########################################################################################
# Mapping network drives
###########################################################################################
#Get PowerShell drives and rename properties

if (-not (Test-RunningAsSystem)) {

	$psDrives = Get-PSDrive | Where-Object { $_.Provider.Name -eq "FileSystem" -and $_.Root -notin @("$env:SystemDrive\", "D:\") } `
	| Select-Object @{N = "DriveLetter"; E = { $_.Name } }, @{N = "Path"; E = { $_.DisplayRoot } }

	# only map drives where group membership applicable
	$driveMappingConfig = Test-GroupMembership -driveMappingConfig $driveMappingConfig -groupMemberships $groupMemberships

	#iterate through all network drive configuration entries
	foreach ($drive in $driveMappingConfig) {

		try {
			#check if variable in unc path exists, e.g. for $env:USERNAME -> resolving
			if ($drive.Path -match '\$env:') {
				$drive.Path = $ExecutionContext.InvokeCommand.ExpandString($drive.Path)
			}

			#if label is null we need to set it to empty in order to avoid error
			if ($null -eq $drive.Label) {
				$drive.Label = ""
			}

			#handle expansion of environment variables in the label
            if ($drive.Label -match '\$env:') {
				$drive.Label = $ExecutionContext.InvokeCommand.ExpandString($drive.Label)
			}

			$exists = $psDrives | Where-Object { $_.Path -eq $drive.Path -or $_.DriveLetter -eq $drive.DriveLetter }
			$process = $true

			if ($null -ne $exists -and $($exists.Path -eq $drive.Path -and $exists.DriveLetter -eq $drive.DriveLetter )) {
				Write-Output "Drive '$($drive.DriveLetter):\' '$($drive.Path)' already exists with correct Drive Letter and Path"
				$process = $false

			}
			else {
				# Mapped with wrong config -> Delete it
				Get-PSDrive | Where-Object { $_.DisplayRoot -eq $drive.Path -or $_.Name -eq $drive.DriveLetter } | Remove-PSDrive -EA SilentlyContinue
			}

			if ($process) {
				Write-Output "Mapping network drive $($drive.Path)"
				$null = New-PSDrive -PSProvider FileSystem -Name $drive.DriveLetter -Root $drive.Path -Description $drive.Label -Persist -Scope global -EA Stop
				(New-Object -ComObject Shell.Application).NameSpace("$($drive.DriveLetter):").Self.Name = $drive.Label
			}
		}
		catch {
			$available = Test-Path $($drive.Path)
			if (-not $available) {
				Write-Error "Unable to access path '$($drive.Path)' verify permissions and authentication!"
			}
			else {
				Write-Error $_.Exception.Message
			}
		}
	}

	# Remove unassigned drives
	if ($removeStaleDrives -and $null -ne $psDrives) {
		$diff = Compare-Object -ReferenceObject $driveMappingConfig -DifferenceObject $psDrives -Property "DriveLetter" -PassThru | Where-Object { $_.SideIndicator -eq "=>" }
		foreach ($unassignedDrive in $diff) {
			Write-Warning "Drive '$($unassignedDrive.DriveLetter)' has not been assigned - removing it..."
			Remove-SmbMapping -LocalPath "$($unassignedDrive.DriveLetter):" -Force -UpdateProfile
		}
	}

	# Fix to ensure drives are mapped as persistent!
	$null = Get-ChildItem -Path HKCU:\Network -ErrorAction SilentlyContinue | ForEach-Object { New-ItemProperty -Name ConnectionType -Value 1 -Path $_.PSPath -Force -ErrorAction SilentlyContinue }
}

###########################################################################################
# End & finish transcript
###########################################################################################

Stop-transcript

###########################################################################################
# Done
###########################################################################################

#!SCHTASKCOMESHERE!#

###########################################################################################
# If this script is running under system (IME) scheduled task is created  (recurring)
###########################################################################################

if (Test-RunningAsSystem) {

	Start-Transcript -Path $(Join-Path -Path $env:temp -ChildPath "IntuneDriveMappingScheduledTask.log")
	Write-Output "Running as System --> creating scheduled task which will run on user logon"

	###########################################################################################
	# Get the current script path and content and save it to the client
	###########################################################################################

	$currentScript = Get-Content -Path $($PSCommandPath)

	$schtaskScript = $currentScript[(0) .. ($currentScript.IndexOf("#!SCHTASKCOMESHERE!#") - 1)]

	$scriptSavePath = $(Join-Path -Path $env:ProgramData -ChildPath "Intune_Scripts")

	if (-not (Test-Path $scriptSavePath)) {

		New-Item -ItemType Directory -Path $scriptSavePath -Force
	}

	$scriptSavePathName = "DriveMapping.ps1"

	$scriptPath = $(Join-Path -Path $scriptSavePath -ChildPath $scriptSavePathName)

	$schtaskScript | Out-File -FilePath $scriptPath -Force

	###########################################################################################
	# Grab PSInvoker
	###########################################################################################

	#This is to create the PSInvoker64.exe, which can be used going forward. This is PSADT's method of running PowerShell scripts hidden
	# and it also has fantatsic error handling and works in 64-bit
	if (-not (Test-Path "$($env:ProgramData)\Intune_Scripts\PSInvoker64.exe")) { 
		$URI = 'https://github.com/JustSomeITAdmin/JustSomeScripts/raw/main/bin/Invoke-AppDeployToolkit.exe'
		$hashCheck = "F36C52BFDB14918B6ACC55C5D0CF13E0AB28AAEA913D244110C05FDEB1844E5C"
		try {
			Start-BitsTransfer -Source $URI -Destination "$($env:TEMP)\PSInvoker64.exe"
			if ((Get-FileHash -Path "$($env:TEMP)\PSInvoker64.exe" -Algorithm SHA256).Hash -eq $hashCheck) { 
				Copy-Item -Path "$($env:TEMP)\PSInvoker64.exe" -Destination "$($env:ProgramData)\Intune_Scripts\PSInvoker64.exe"
			}
			else {
				Write-Output "This is a hash mismatch!"
				exit 1
			}
		}
		catch {
			#Nothing we can do here
		}
	}
	Unblock-File -Path "$($env:ProgramData)\Intune_Scripts\PSInvoker64.exe" 

	###########################################################################################
	# Register a scheduled task to run for all users and execute the script on logon
	###########################################################################################

	$schtaskName = "IntuneDriveMapping"
	$schtaskDescription = "Map network drives from intune-drive-mapping-generator."

	$trigger = New-ScheduledTaskTrigger -AtLogOn
	#Execute task in users context
	$principal = New-ScheduledTaskPrincipal -GroupId "S-1-5-32-545" -Id "Author"
	#call the vbscript helper and pass the PosH script as argument
	$action = New-ScheduledTaskAction -Execute "$($env:ProgramData)\Intune_Scripts\PSInvoker64.exe" -Argument "$scriptPath"
	#$action = New-ScheduledTaskAction -Execute $wscriptPath -Argument "`"$dummyScriptPath`" `"$scriptPath`""
	$settings = New-ScheduledTaskSettingsSet -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries

	$null = Register-ScheduledTask -TaskName $schtaskName -Trigger $trigger -Action $action  -Principal $principal -Settings $settings -Description $schtaskDescription -Force

	Start-ScheduledTask -TaskName $schtaskName

	Stop-Transcript
}

###########################################################################################
# Done
###########################################################################################
